import { sertifikasiPegawai } from './sertifikasiPegawai';
import { keluargaPegawai } from './keluargaPegawai';
import { riwayatKesehatanPegawai } from './riwayatKesehatanPegawai';
import { hobiPegawai } from './hobiPegawai';
import { jenisKontrakPegawai } from './jenisKontrakPegawai';
import { riwayatPendidikanPegawai } from './riwayatPendidikanPegawai';
import { rekeningPegawai } from './rekeningPegawai';
import { riwayatPelatihanPegawai } from './riwayatPelatihanPegawai';
import { editSertifikasiPegawai } from './editSertifikatPegawai';
import { deleteSertifikasiPegawai } from './deleteSertifikatPegawai';
import { editKeluargaPegawai } from './editKeluargaPegawai';
import { deleteKeluargaPegawai } from './deleteKeluargaPegawai';
import { editRiwayatKesehatanPegawai } from './editRiwayatKesehatanPegawai';
import { deleteRiwayatKesehatanPegawai } from './deleteRiwayatKesehatanPegawai';
import { editHobiPegawai } from './editHobiPegawai';
import { deleteHobiPegawai } from './deleteHobiPegawai';
import { editJenisKontrakPegawai } from './editJenisKontrakPegawai';
import { deleteJenisKontrakPegawai } from './deleteJenisKontrakPegawai';
import { editRiwayatPendidikanPegawai } from './editRiwayatPendidikanPegawai';
import { deleteRiwayatPendidikanPegawai } from './deleteRiwayatPendidikanPegawai';
import { editRekeningPegawai } from './editRekeningPegawai';
import { deleteRekeningPegawai } from './deleteRekeningPegawai';
import { editRiwayatPelatihanPegawai } from './editRiwayatPelatihanPegawai';
import { deleteRiwayatPelatihanPegawai } from './deleteRiwayatPelatihanPegawai';

export const detailPegawai = () => {
    cy.get('table tr:last-child a.btn.bg-teal.btn-sm.text-white') 
    .invoke('attr', 'href') 
    .then((href) => {
    const lastId = href.match(/Id=(\d+)/)[1];
    cy.get(`a.btn.bg-teal.btn-sm.text-white[href="/Pegawai/Detail?Id=${lastId}"]`).click();
    cy.url().should('include', `/Pegawai/Detail?Id=${lastId}`);
    });

    // sertifikasiPegawai();
    // cy.wait(2000);
    // editSertifikasiPegawai();
    // cy.wait(2000);
    // deleteSertifikasiPegawai();
    // cy.wait(2000);
    // keluargaPegawai();
    // cy.wait(2000);
    // editKeluargaPegawai();
    // cy.wait(2000);
    // deleteKeluargaPegawai();
    // cy.wait(2000);
    // riwayatKesehatanPegawai();
    // cy.wait(2000);
    // editRiwayatKesehatanPegawai();
    // cy.wait(2000);
    // deleteRiwayatKesehatanPegawai();
    // cy.wait(2000);
    // hobiPegawai();
    // cy.wait(2000);
    // editHobiPegawai();
    // cy.wait(2000);
    // deleteHobiPegawai();
    // cy.wait(2000);
    // jenisKontrakPegawai();
    // cy.wait(2000);
    // editJenisKontrakPegawai();
    // cy.wait(2000);
    // deleteJenisKontrakPegawai();
    // cy.wait(2000);
    // riwayatPendidikanPegawai();
    // cy.wait(2000);
    // editRiwayatPendidikanPegawai();
    // cy.wait(2000);
    // deleteRiwayatPendidikanPegawai();
    // cy.wait(2000);
    // rekeningPegawai();
    // cy.wait(2000);
    // editRekeningPegawai();
    // cy.wait(2000);
    // deleteRekeningPegawai();
    // cy.wait(2000);
    riwayatPelatihanPegawai();
    cy.wait(2000);
    editRiwayatPelatihanPegawai();
    cy.wait(2000);
    deleteRiwayatPelatihanPegawai();
    cy.wait(2000);
};